package hello;

//https://medium.com/@gustavo.ponce.ch/spring-boot-spring-mvc-spring-security-mysql-a5d8545d837d

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

//@Controller    // This means that this class is a Controller
@RequestMapping(path = "/test") // This means URL's start with /test (after Application path)
@Service("ClientService")
public class ClientServiceImpl implements ClientService {
    // Autowired means to get the bean called somethingRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private ClientRepository clientRepository;
    @Autowired
    private FeedbackRepository feedbackRepository;
    @Autowired
    private BCryptPasswordEncoder bCryptPasswordEncoder;

    @Override
    public Client findClientByUsername(String username) {
        return clientRepository.findByUsername(username);
    }

    @Override
    public void saveClient(Client c) {
        c.setPassword(bCryptPasswordEncoder.encode(c.getPassword()));
        // c.setActive(1); //TODO: is active necessary?
        if (c.getId() % 2 == 0) {
            c.setIsAdmin(true);
        }
        clientRepository.save(c);
    }

}