package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.User;
import hello.UserRepository;

import java.sql.Date;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/test") // This means URL's start with /test (after Application path)
public class MainController {
    // Autowired means to get the bean called somethingRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private Client_info_tableRepository client_info_tableRepository;
    @Autowired
    private Feedback_tableRepository feedback_tableRepository;

    // Map ONLY GET Requests
    @GetMapping(path = "/addClient")
    // @ResponseBody means the returned String is the response, not a view name
    public @ResponseBody
    // @RequestParam means it is a parameter from the GET or POST request

    String addNewClient(@RequestParam String user_name
            , @RequestParam String user_pw) {
        Client_info_table n = new Client_info_table();
        n.setUser_name(user_name);
        n.setUser_pw(user_pw);
        client_info_tableRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/addFeedback")
    public @ResponseBody
    String addNewFeedback(@RequestParam int rating,
                          @RequestParam String comment) {
        Feedback_table n = new Feedback_table();
        n.setRating(rating);
        n.setComment(comment);
        //java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());        n.setFeedback_date(date);
        //Date date = new Date();
        //TODO: current date
        feedback_tableRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/getAllClients")
    public @ResponseBody
    Iterable<Client_info_table> getAllClients() {
        // This returns a JSON or XML with the users
        return client_info_tableRepository.findAll();
    }

    @GetMapping(path = "/getAllFeedback")
    public @ResponseBody
    Iterable<Feedback_table> getAllFeedback() {
        return feedback_tableRepository.findAll();
    }


}